apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../stable
transformers:
- ../../images/prow-gke-release-staging-head
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: csi-gce-pd-controller
  path: leader-election-flag.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: csi-gce-pd-controller
  path: volume-inuse-error-handler.yaml
