# csi-provisioner
# "--leader-election-type=leases"
- op: remove
  path: /spec/template/spec/containers/0/args/5

# csi-provisioner
# "--enable-leader-election" 
- op: remove
  path: /spec/template/spec/containers/0/args/4

# csi-provisioner
- op: add	
  path: /spec/template/spec/containers/0/args/-	
  value: "--leader-election"

# csi-provisioner
- op: add
  path: /spec/template/spec/containers/0/args/-	
  value: "--default-fstype=ext4"

# csi-resizer
- op: add
  path: /spec/template/spec/containers/2/args/-
  value: "--handle-volume-inuse-error=false"
